site_name: PoC Github Pages y Wiki
site_url: https://cady-contreras-ntt.github.io/PoC_Public_doc
repo_url: https://github.com/cady-contreras-ntt/PoC_Public_doc
repo_name: GitHub

theme:
  name: material
  language: es
  features:
    - navigation.expand
    - navigation.sections
    - navigation.instant
    - search.suggest
    - content.code.copy

nav:
  - Inicio: index.md
  - Bitbucket:
      - Introducción: bitbucket.md

markdown_extensions:
  - toc:
      permalink: true
  - admonition
  - codehilite
  - footnotes
  - tables
  - pymdownx.highlight
  - pymdownx.inlinehilite
  - pymdownx.superfences
  - pymdownx.details

plugins:
  - search
